dist: trusty
sudo: enabled
language: cpp
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    cd ${DEPS_DIR}/cmake && ./bootstrap && make
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

before_script:
  - mkdir ../build
  - cd ../build

script:
  - CXX=clang++-5.0 && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" \
    -DBUILD_SHARED=LIBS=True -DLLVM_USE_SPLIT_DWARF=True \
    -DLLVM_OPTIMIZED_TABLEGEN=True \
    -DLLVM_BUILD_TESTS=True \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="RISCV" ../llvm-riscv
