dist: trusty
sudo: false
language: cpp
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

before_script:
  - mkdir ../build
  - cd ../build

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" \
    -DBUILD_SHARED=LIBS=True -DLLVM_USE_SPLIT_DWARF=True \
    -DLLVM_OPTIMIZED_TABLEGEN=True \
    -DLLVM_BUILD_TESTS=True \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="RISCV" ../llvm-riscv
